class Autogenerated {
  bool? status;
  int? code;
  String? message;
  Data? data;

  Autogenerated({this.status, this.code, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['status'] = status;
    data['code'] = code;
    data['message'] = message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  int? totalSize;
  List<Charges>? helperLeaves;

  Data({this.totalSize, this.helperLeaves});

  Data.fromJson(Map<String, dynamic> json) {
    totalSize = json['total_size'];
    if (json['helperLeaves'] != null) {
      helperLeaves = <Charges>[];
      json['helperLeaves'].forEach((v) {
        helperLeaves!.add(new Charges.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['total_size'] = totalSize;
    if (helperLeaves != null) {
      data['helperLeaves'] = helperLeaves!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Charges {
  String? serviceChargeId;
  int? oneTimeServiceCharge;
  int? subscriptionServiceCharge;
  int? transportationCharges;
  int? cancellationCharge;
  Audit? audit;

  Charges({
    this.serviceChargeId,
    this.oneTimeServiceCharge,
    this.subscriptionServiceCharge,
    this.transportationCharges,
    this.cancellationCharge,
    this.audit,
  });

  Charges.fromJson(Map<String, dynamic> json) {
    serviceChargeId = json['service_charge_id'];
    oneTimeServiceCharge = json['one_time_service_charge'];
    subscriptionServiceCharge = json['subscription_service_charge'];
    transportationCharges = json['transportation_charge'];
    cancellationCharge = json['cancellation_charge'];
    audit = json['audit'] != null ? new Audit.fromJson(json['audit']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['service_charge_id'] = serviceChargeId;
    data['one_time_service_charge'] = oneTimeServiceCharge;
    data['subscription_service_charge'] = subscriptionServiceCharge;
    data['transportation_charge'] = transportationCharges;
    data['cancellation_charge'] = cancellationCharge;
    if (audit != null) {
      data['audit'] = audit!.toJson();
    }
    return data;
  }
}

class Audit {
  String? createdAt;
  String? createdBy;
  String? updatedAt;
  String? updatedBy;

  Audit({this.createdAt, this.createdBy, this.updatedAt, this.updatedBy});

  Audit.fromJson(Map<String, dynamic> json) {
    createdAt = json['created_at'];
    createdBy = json['created_by'];
    updatedAt = json['updated_at'];
    updatedBy = json['updated_by'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['created_at'] = createdAt;
    data['created_by'] = createdBy;
    data['updated_at'] = updatedAt;
    data['updated_by'] = updatedBy;
    return data;
  }
}
