import 'dart:ffi';

class Autogenerated {
  bool? status;
  int? code;
  String? message;
  OrderDetailModel? data;

  Autogenerated({this.status, this.code, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    code = json['code'];
    message = json['message'];
    data = json['data'] != null
        ? new OrderDetailModel.fromJson(json['data'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['code'] = this.code;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

double _toDouble(dynamic value) {
  if (value == null) return 0.0;

  if (value is int) return value.toDouble();
  if (value is double) return value;
  if (value is String) return double.tryParse(value) ?? 0.0;

  return 0.0;
}

class OrderDetailModel {
  String? sId;
  String? orderId;
  String? quotationId;
  String? userId;
  String? helperId;
  String? date;
  String? service;
  String? placeType;
  String? orderType;
  double? amount;
  String? paymentMode;
  String? paymentStatus;
  String? renewalDate;
  String? comment;
  Audit? audit;
  String? status;
  String? orderReference;
  int? subscriptionDurationInDays;
  String? startDate;
  String? endDate;
  bool? isDelete;
  String? startTime;
  double? serviceCharge;
  double? transportationCharge;
  double? distance;
  String? duration;
  String? addressType;
  String? addressLine1;
  String? addressLine2;
  String? blockNo;
  String? houseNo;
  String? city;
  String? state;
  String? pincode;
  UserDetails? userDetails;
  HelperDetails? helperDetails;

  OrderDetailModel({
    this.sId,
    this.orderId,
    this.quotationId,
    this.userId,
    this.helperId,
    this.date,
    this.service,
    this.placeType,
    this.orderType,
    this.amount,
    this.paymentMode,
    this.paymentStatus,
    this.renewalDate,
    this.comment,
    this.audit,
    this.status,
    this.orderReference,
    this.subscriptionDurationInDays,
    this.startDate,
    this.endDate,
    this.isDelete,
    this.startTime,
    this.serviceCharge,
    this.transportationCharge,
    this.distance,
    this.duration,
    this.addressType,
    this.addressLine1,
    this.addressLine2,
    this.blockNo,
    this.houseNo,
    this.city,
    this.state,
    this.userDetails,
    this.helperDetails,
  });

  OrderDetailModel.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    orderId = json['order_id'];
    quotationId = json['quotation_id'];
    userId = json['user_id'];
    helperId = json['helper_id'];
    date = json['date'];
    service = json['service'];
    placeType = json['place_type'];
    orderType = json['order_type'];
    paymentMode = json['payment_mode'];
    paymentStatus = json['payment_status'];
    renewalDate = json['renewal_date'];
    comment = json['comment'];
    audit = json['audit'] != null ? new Audit.fromJson(json['audit']) : null;
    status = json['status'];
    orderReference = json['order_reference'];
    subscriptionDurationInDays = json['subscription_duration_in_days'];
    startDate = json['start_date'];
    endDate = json['end_date'];
    isDelete = json['is_delete'];
    startTime = json['start_time'];
    amount = _toDouble(json['amount']);
    serviceCharge = _toDouble(json['service_charge']);
    transportationCharge = _toDouble(json['transportation_charge']);
    distance = _toDouble(json['distance']);
    duration = json['duration'];
    addressType = json['address_type'];
    addressLine1 = json['address_line_1'];
    addressLine2 = json['address_line_2'];
    blockNo = json['block_no'];
    houseNo = json['house_no'];
    city = json['city'];
    state = json['state'];
    pincode = json['pin_code'];
    userDetails = json['userDetails'] != null
        ? new UserDetails.fromJson(json['userDetails'])
        : null;
    helperDetails = json['helperDetails'] != null
        ? new HelperDetails.fromJson(json['helperDetails'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['order_id'] = this.orderId;
    data['quotation_id'] = this.quotationId;
    data['user_id'] = this.userId;
    data['helper_id'] = this.helperId;
    data['date'] = this.date;
    data['service'] = this.service;
    data['place_type'] = this.placeType;
    data['order_type'] = this.orderType;
    data['amount'] = this.amount;
    data['payment_mode'] = this.paymentMode;
    data['payment_status'] = this.paymentStatus;
    data['renewal_date'] = this.renewalDate;
    data['comment'] = this.comment;
    data['pin_code'] = this.comment;
    if (this.audit != null) {
      data['audit'] = this.audit!.toJson();
    }
    data['status'] = this.status;
    data['order_reference'] = this.orderReference;
    data['subscription_duration_in_days'] = this.subscriptionDurationInDays;
    data['start_date'] = this.startDate;
    data['end_date'] = this.endDate;
    data['is_delete'] = this.isDelete;
    data['start_time'] = this.startTime;
    data['service_charge'] = this.serviceCharge;
    data['transportation_charge'] = this.transportationCharge;
    data['distance'] = this.distance;
    data['duration'] = this.duration;
    data['address_type'] = this.addressType;
    data['address_line_1'] = this.addressLine1;
    data['address_line_2'] = this.addressLine2;
    data['block_no'] = this.blockNo;
    data['house_no'] = this.houseNo;
    data['city'] = this.city;
    data['state'] = this.state;
    if (this.userDetails != null) {
      data['userDetails'] = this.userDetails!.toJson();
    }
    if (this.helperDetails != null) {
      data['helperDetails'] = this.helperDetails!.toJson();
    }
    return data;
  }
}

class Audit {
  String? createdAt;
  String? createdBy;
  String? updatedAt;
  String? updatedBy;

  Audit({this.createdAt, this.createdBy, this.updatedAt, this.updatedBy});

  Audit.fromJson(Map<String, dynamic> json) {
    createdAt = json['created_at'];
    createdBy = json['created_by'];
    updatedAt = json['updated_at'];
    updatedBy = json['updated_by'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['created_at'] = this.createdAt;
    data['created_by'] = this.createdBy;
    data['updated_at'] = this.updatedAt;
    data['updated_by'] = this.updatedBy;
    return data;
  }
}

class UserDetails {
  String? sId;
  String? userId;
  String? firstName;
  String? lastName;
  String? city;
  String? pinCode;
  String? addressLine1;
  String? addressLine2;
  String? state;
  String? email;
  String? password;
  String? contactNo;
  String? role;
  String? status;
  Audit? audit;
  String? otp;
  String? profileImage;
  String? addressType;
  double? distance;
  List<Addresses>? addresses;

  UserDetails({
    this.sId,
    this.userId,
    this.firstName,
    this.lastName,
    this.city,
    this.pinCode,
    this.addressLine1,
    this.addressLine2,
    this.state,
    this.email,
    this.password,
    this.contactNo,
    this.role,
    this.status,
    this.audit,
    this.otp,
    this.profileImage,
    this.addressType,
    this.distance,
    this.addresses,
  });

  UserDetails.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    userId = json['user_id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    city = json['city'];
    pinCode = json['pin_code'];
    addressLine1 = json['address_line_1'];
    addressLine2 = json['address_line_2'];
    state = json['state'];
    email = json['email'];
    password = json['password'];
    contactNo = json['contact_no'];
    role = json['role'];
    status = json['status'];
    audit = json['audit'] != null ? new Audit.fromJson(json['audit']) : null;
    otp = json['otp'];
    profileImage = json['profile_image'];
    addressType = json['address_type'];
    distance = json['distance'];
    if (json['addresses'] != null) {
      addresses = <Addresses>[];
      json['addresses'].forEach((v) {
        addresses!.add(new Addresses.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['user_id'] = this.userId;
    data['first_name'] = this.firstName;
    data['last_name'] = this.lastName;
    data['city'] = this.city;
    data['pin_code'] = this.pinCode;
    data['address_line_1'] = this.addressLine1;
    data['address_line_2'] = this.addressLine2;
    data['state'] = this.state;
    data['email'] = this.email;
    data['password'] = this.password;
    data['contact_no'] = this.contactNo;
    data['role'] = this.role;
    data['status'] = this.status;
    if (this.audit != null) {
      data['audit'] = this.audit!.toJson();
    }
    data['otp'] = this.otp;
    data['profile_image'] = this.profileImage;
    data['address_type'] = this.addressType;
    data['distance'] = this.distance;
    if (this.addresses != null) {
      data['addresses'] = this.addresses!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Addresses {
  String? addressType;
  String? addressLine1;
  String? addressLine2;
  String? blockNo;
  String? city;
  String? state;
  String? pinCode;
  double? distance;

  Addresses({
    this.addressType,
    this.addressLine1,
    this.addressLine2,
    this.blockNo,
    this.city,
    this.state,
    this.pinCode,
    this.distance,
  });

  Addresses.fromJson(Map<String, dynamic> json) {
    addressType = json['address_type'];
    addressLine1 = json['address_line_1'];
    addressLine2 = json['address_line_2'];
    blockNo = json['block_no'];
    city = json['city'];
    state = json['state'];
    pinCode = json['pin_code'];
    distance = _toDouble(json['distance']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['address_type'] = this.addressType;
    data['address_line_1'] = this.addressLine1;
    data['address_line_2'] = this.addressLine2;
    data['block_no'] = this.blockNo;
    data['city'] = this.city;
    data['state'] = this.state;
    data['pin_code'] = this.pinCode;
    data['distance'] = this.distance;
    return data;
  }
}

class HelperDetails {
  String? sId;
  String? helperId;
  String? userType;
  String? firstName;
  String? lastName;
  String? phoneNo;
  String? employmentType;
  String? dateOfJoining;
  String? dateOfExit;
  String? addressLine1;
  String? addressLine2;
  Availability? availability;
  String? weekOffDay;
  String? city;
  String? state;
  String? pinCode;
  String? highestEducation;
  String? haveVehicle;
  List<String>? knownLanguages;
  Audit? audit;
  int? perHourPayout;
  int? monthlyPayout;
  String? aadharCard;
  String? panCard;
  String? lightBill;
  String? status;
  bool? isDelete;

  HelperDetails({
    this.sId,
    this.helperId,
    this.userType,
    this.firstName,
    this.lastName,
    this.phoneNo,
    this.employmentType,
    this.dateOfJoining,
    this.dateOfExit,
    this.addressLine1,
    this.addressLine2,
    this.availability,
    this.weekOffDay,
    this.city,
    this.state,
    this.pinCode,
    this.highestEducation,
    this.haveVehicle,
    this.knownLanguages,
    this.audit,
    this.perHourPayout,
    this.monthlyPayout,
    this.aadharCard,
    this.panCard,
    this.lightBill,
    this.status,
    this.isDelete,
  });

  HelperDetails.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    helperId = json['helper_id'];
    userType = json['user_type'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    phoneNo = json['phone_no'];
    employmentType = json['employment_type'];
    dateOfJoining = json['date_of_joining'];
    dateOfExit = json['date_of_exit'];
    addressLine1 = json['address_line_1'];
    addressLine2 = json['address_line_2'];
    availability = json['availability'] != null
        ? new Availability.fromJson(json['availability'])
        : null;
    weekOffDay = json['week_off_day'];
    city = json['city'];
    state = json['state'];
    pinCode = json['pin_code'];
    highestEducation = json['highest_education'];
    haveVehicle = json['have_vehicle'];
    knownLanguages = json['known_languages'].cast<String>();
    audit = json['audit'] != null ? new Audit.fromJson(json['audit']) : null;
    perHourPayout = json['per_hour_payout'];
    monthlyPayout = json['monthly_payout'];
    aadharCard = json['aadhar_card'];
    panCard = json['pan_card'];
    lightBill = json['light_bill'];
    status = json['status'];
    isDelete = json['is_delete'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['helper_id'] = this.helperId;
    data['user_type'] = this.userType;
    data['first_name'] = this.firstName;
    data['last_name'] = this.lastName;
    data['phone_no'] = this.phoneNo;
    data['employment_type'] = this.employmentType;
    data['date_of_joining'] = this.dateOfJoining;
    data['date_of_exit'] = this.dateOfExit;
    data['address_line_1'] = this.addressLine1;
    data['address_line_2'] = this.addressLine2;
    if (this.availability != null) {
      data['availability'] = this.availability!.toJson();
    }
    data['week_off_day'] = this.weekOffDay;
    data['city'] = this.city;
    data['state'] = this.state;
    data['pin_code'] = this.pinCode;
    data['highest_education'] = this.highestEducation;
    data['have_vehicle'] = this.haveVehicle;
    data['known_languages'] = this.knownLanguages;
    if (this.audit != null) {
      data['audit'] = this.audit!.toJson();
    }
    data['per_hour_payout'] = this.perHourPayout;
    data['monthly_payout'] = this.monthlyPayout;
    data['aadhar_card'] = this.aadharCard;
    data['pan_card'] = this.panCard;
    data['light_bill'] = this.lightBill;
    data['status'] = this.status;
    data['is_delete'] = this.isDelete;
    return data;
  }
}

class Availability {
  String? startTime;
  String? endTime;

  Availability({this.startTime, this.endTime});

  Availability.fromJson(Map<String, dynamic> json) {
    startTime = json['start_time'];
    endTime = json['end_time'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['start_time'] = this.startTime;
    data['end_time'] = this.endTime;
    return data;
  }
}
